name: Shared workflow for validating push requests

on:
  workflow_call:
    inputs:
      branch:
        required: true
        type: string
  
jobs:
  validate:
    runs-on: ubuntu-latest
    steps:
    
      # Setup NodeJS Active LTS (20 currently, moving to 22 as the next LTS)
      - uses: actions/setup-node@v4
        with:
          node-version: 22

      # Checkout the relevant content for push or workflow_dispatch
      - name: Checkout For Push or Workflow Dispatch
        uses: actions/checkout@v4
        with:
           ref: ${{ inputs.branch }}
           fetch-depth: 0    
      
      # Install hdoc-tools globally
      - name: Install hdoc-tools
        run: npm install hdoc-tools -g
     
     # Run hdoc validate against checked-out content
      - name: Perform Validation
        id: hdocbuild
        run: |
          if result=`hdoc validate 2>&1`; then
              printf "Build Success!\n\n"
              printf "$result"
              exit 0
          else
            #valout=$(echo "$result" | awk '/Validation Output/,0')
            printf "Build Failed!\n\n-----------------------\n"
            printf "$result"
            exit 1
          fi
  
      # If build validation is successful, echo message
      - name: Build Success
        if: success()
        run: echo "::notice::Build validation passed successfully."
